#!/bin/sh
#
# Start web server....
#

case "$1" in
  start)
	printf "Starting web server: "
	cd /usr/lib/webui/
	python manage.py runserver 192.168.168.168:80 >>/tmp/web_ui_python.log  2>&1 &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	cd -
	;;
  stop)
	printf "Stopping web server : "
	killall -s 9 python
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  netready|netup|netdown|netchange) ;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

