#!/bin/sh

case "$1" in
        start)
                printf "Start face recognize app: "
		/usr/bin/rknn_demo  >>/tmp/rknn_demo.log  2>&1 &
                ;;
        stop)
		killall rknn_demo
		printf "stop face recognize app"
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
exit 0

